name: CI for Emacs packages

on:
  push:
    paths-ignore:
      - '*.org'
    branches:
      - main
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/checkout@v2

      - name: Print emacs version
        run: |
          emacs --version

      - name: Install dependency
        run: sudo apt install libarchive-tools

      - name: Check startup
        run: make startup

      - name: Backup packages for elpa
        run: |
          mkdir -p "/tmp/myelpa"
          make backup

      - name: Commit files for elpa
        run: |
          cd /tmp/myelpa
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "$(TZ=UTC-8 date '+%y/%m/%d %H:%M:%S')"

      - name: Push for elpa
        uses: ad-m/github-push-action@master
        with:
          directory: /tmp/myelpa
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: elpa
          force: true

      - name: Backup packages for module
        run: |
          cp -vR ~/.emacs.d/elpa /tmp/mymodule

      - name: Delete files for module
        run: |
          cd /tmp/mymodule
          rm -rf archives
          rm -rf elpa-mirror*
          rm -rf quelpa*
          find . -name '*.elc' | xargs rm -rf
          find . -name '.signed' | xargs rm -rf

      - name: Commit files for module
        run: |
          cd /tmp/mymodule
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "$(TZ=UTC-8 date '+%y/%m/%d %H:%M:%S')"

      - name: Push for module
        uses: ad-m/github-push-action@master
        with:
          directory: /tmp/mymodule
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: module
          force: true
